# This is a basic workflow to help you get started with Actions

name: README Update

permissions:
  contents: write

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  perform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run script
      run: bundle exec ruby ./scripts/rb/update_readme.rb
    - name: Commit and push if changed
      run: |
        if git diff --quiet -- README.md; then
          echo "No README changes."
          exit 0
        fi

        git add README.md
        git config user.email "github-action-bot@example.com"
        git config user.name "GitHub Action Bot"
        git commit -m "chore: update README"
        git push
